INSERT INTO vendor VALUES ("LibDib");
INSERT INTO vendor VALUES ("Pepsi Co");
INSERT INTO vendor VALUES ("Tyson Foods");
INSERT INTO vendor VALUES ("U.S Foods");
INSERT INTO vendor VALUES ("Coca-Cola");
INSERT INTO vendor VALUES ("Amazon Fresh");
INSERT INTO vendor VALUES ("Nestle");
INSERT INTO vendor VALUES ("General Mills");
INSERT INTO vendor VALUES ("Kraft Heinz");
INSERT INTO vendor VALUES ("Dole");
INSERT INTO vendor VALUES ("Chiquita");
INSERT INTO vendor VALUES ("Land O'Lakes");
INSERT INTO vendor VALUES ("Quaker Oats");
INSERT INTO vendor VALUES ("Fruit of the Loom");
INSERT INTO vendor VALUES ("Red Bull");
INSERT INTO vendor VALUES ("McCormick");
INSERT INTO vendor VALUES ("Clorox");
INSERT INTO vendor VALUES ("Glad");
INSERT INTO vendor VALUES ("Bounty");
INSERT INTO vendor VALUES ("Northern Tool");